export const runtime = "nodejs";

import { NextResponse } from "next/server";
import connectDB from "@/lib/mongoose";
import { Property } from "@/models";
import { randomUUID } from "crypto";

function makeId() {
  return `prop-${randomUUID().slice(0, 8)}`;
}

function makeSlug(title) {
  return title.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}

const now = new Date().toISOString();

const SEED_PROPERTIES = [
  // ── SALE · RESIDENTIAL ──────────────────────────────────────────────
  {
    title: "3 BHK Luxury Apartment in Bandra West",
    price: "₹4.2 Cr",
    priceCr: 4.2,
    location: "Bandra West, Mumbai",
    category: "sale",
    propertyFor: "residential",
    type: "Apartment",
    status: "Ready",
    sqft: "1,850",
    beds: 3,
    baths: 3,
    tag: "Premium",
    description: "Stunning 3 BHK in the heart of Bandra West with sea-facing views, modular kitchen, and premium fittings. Steps from Linking Road.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "4 BHK Villa in Powai",
    price: "₹6.5 Cr",
    priceCr: 6.5,
    location: "Powai, Mumbai",
    category: "sale",
    propertyFor: "residential",
    type: "Villa",
    status: "Ready",
    sqft: "3,200",
    beds: 4,
    baths: 4,
    tag: "Luxury",
    description: "Independent 4 BHK villa with private garden, home theatre, and lake views in one of Mumbai's most sought-after localities.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "2 BHK Flat in Andheri East",
    price: "₹1.45 Cr",
    priceCr: 1.45,
    location: "Andheri East, Mumbai",
    category: "sale",
    propertyFor: "residential",
    type: "Apartment",
    status: "Ready",
    sqft: "920",
    beds: 2,
    baths: 2,
    tag: "Value Pick",
    description: "Well-maintained 2 BHK with good connectivity to Metro and Western Express Highway. Ideal for working professionals.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "3 BHK Premium Flat in Worli",
    price: "₹8.9 Cr",
    priceCr: 8.9,
    location: "Worli, Mumbai",
    category: "sale",
    propertyFor: "residential",
    type: "Apartment",
    status: "Ready",
    sqft: "2,100",
    beds: 3,
    baths: 3,
    tag: "Ultra Luxury",
    description: "High-floor apartment in Worli's premium tower with panoramic sea views, private lobby, and concierge service.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "2 BHK in Thane West",
    price: "₹95 L",
    priceCr: 0.95,
    location: "Thane West, Thane",
    category: "sale",
    propertyFor: "residential",
    type: "Apartment",
    status: "Ready",
    sqft: "850",
    beds: 2,
    baths: 2,
    tag: "Affordable",
    description: "Compact and well-planned 2 BHK in a gated society with amenities including gym, club house, and 24/7 security.",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "3 BHK in Pune Kalyani Nagar",
    price: "₹1.85 Cr",
    priceCr: 1.85,
    location: "Kalyani Nagar, Pune",
    category: "sale",
    propertyFor: "residential",
    type: "Apartment",
    status: "Ready",
    sqft: "1,350",
    beds: 3,
    baths: 2,
    tag: "Premium",
    description: "Spacious 3 BHK in Kalyani Nagar's premium residential tower, close to Aga Khan Palace and major IT parks.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1400&q=80",
  },

  // ── SALE · COMMERCIAL ──────────────────────────────────────────────
  {
    title: "Grade A Office Space in BKC",
    price: "₹12 Cr",
    priceCr: 12,
    location: "Bandra Kurla Complex, Mumbai",
    category: "sale",
    propertyFor: "commercial",
    type: "Office",
    status: "Ready",
    sqft: "3,500",
    beds: 0,
    baths: 4,
    tag: "Grade A",
    description: "Premium Grade A office space in BKC — Mumbai's premier business district. Floor-to-ceiling glass, raised flooring, and dedicated parking.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "Retail Shop in Linking Road",
    price: "₹3.2 Cr",
    priceCr: 3.2,
    location: "Linking Road, Bandra, Mumbai",
    category: "sale",
    propertyFor: "commercial",
    type: "Retail",
    status: "Ready",
    sqft: "650",
    beds: 0,
    baths: 1,
    tag: "High Street",
    description: "Prime retail unit on Linking Road — Mumbai's most iconic shopping street. Ground floor with high footfall and excellent brand visibility.",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "Office Floor in Powai IT Hub",
    price: "₹5.5 Cr",
    priceCr: 5.5,
    location: "Powai, Mumbai",
    category: "sale",
    propertyFor: "commercial",
    type: "Office",
    status: "Ready",
    sqft: "2,200",
    beds: 0,
    baths: 3,
    tag: "IT Zone",
    description: "Full office floor in Powai's established IT hub. Plug-and-play setup with modular workstations, server room, and cafeteria.",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=80",
  },

  // ── RENT · RESIDENTIAL ──────────────────────────────────────────────
  {
    title: "2 BHK Furnished Flat in Juhu",
    price: "₹85,000/mo",
    priceCr: 0.102,
    location: "Juhu, Mumbai",
    category: "rent",
    propertyFor: "residential",
    type: "Apartment",
    status: "Ready",
    sqft: "1,100",
    beds: 2,
    baths: 2,
    tag: "Furnished",
    description: "Fully furnished 2 BHK in Juhu near the beach. Equipped kitchen, air conditioning throughout, and covered parking.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "3 BHK Semi-Furnished in Goregaon East",
    price: "₹55,000/mo",
    priceCr: 0.066,
    location: "Goregaon East, Mumbai",
    category: "rent",
    propertyFor: "residential",
    type: "Apartment",
    status: "Ready",
    sqft: "1,400",
    beds: 3,
    baths: 2,
    tag: "Semi-Furnished",
    description: "Spacious 3 BHK with modular kitchen and wardrobes in all rooms. Close to metro and Oberoi Mall.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "1 BHK Studio in Malad West",
    price: "₹28,000/mo",
    priceCr: 0.0336,
    location: "Malad West, Mumbai",
    category: "rent",
    propertyFor: "residential",
    type: "Studio",
    status: "Ready",
    sqft: "480",
    beds: 1,
    baths: 1,
    tag: "Budget",
    description: "Compact and cozy studio apartment ideal for working professionals. Well-connected to Western Line and Malad Metro.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "4 BHK Luxury Flat in Prabhadevi",
    price: "₹2.5 L/mo",
    priceCr: 0.3,
    location: "Prabhadevi, Mumbai",
    category: "rent",
    propertyFor: "residential",
    type: "Apartment",
    status: "Ready",
    sqft: "2,800",
    beds: 4,
    baths: 4,
    tag: "Luxury",
    description: "Expansive 4 BHK with dedicated servant quarters, private terrace, and sea views from the 28th floor of a premium tower.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "2 BHK in Hinjewadi Phase 1, Pune",
    price: "₹22,000/mo",
    priceCr: 0.0264,
    location: "Hinjewadi, Pune",
    category: "rent",
    propertyFor: "residential",
    type: "Apartment",
    status: "Ready",
    sqft: "880",
    beds: 2,
    baths: 2,
    tag: "IT Corridor",
    description: "Well-maintained 2 BHK near Hinjewadi IT Park. Ideal for IT professionals. Gated community with 24/7 security.",
    image: "https://images.unsplash.com/photo-1599427303058-f04cbcf4756f?auto=format&fit=crop&w=1400&q=80",
  },

  // ── RENT · COMMERCIAL ──────────────────────────────────────────────
  {
    title: "Office Space in Lower Parel",
    price: "₹1.8 L/mo",
    priceCr: 0.216,
    location: "Lower Parel, Mumbai",
    category: "rent",
    propertyFor: "commercial",
    type: "Office",
    status: "Ready",
    sqft: "2,500",
    beds: 0,
    baths: 3,
    tag: "Co-working Ready",
    description: "Modern open-plan office in Lower Parel's bustling commercial corridor. Plug-and-play infrastructure with high-speed internet.",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "Retail Space in Inorbit Mall, Vashi",
    price: "₹95,000/mo",
    priceCr: 0.114,
    location: "Vashi, Navi Mumbai",
    category: "rent",
    propertyFor: "commercial",
    type: "Retail",
    status: "Ready",
    sqft: "800",
    beds: 0,
    baths: 1,
    tag: "Mall Space",
    description: "Premium retail unit in a high-footfall mall environment in Vashi. Ideal for fashion, F&B, or lifestyle brands.",
    image: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "Warehouse in Bhiwandi Logistics Hub",
    price: "₹3.5 L/mo",
    priceCr: 0.42,
    location: "Bhiwandi, Thane",
    category: "rent",
    propertyFor: "commercial",
    type: "Warehouse",
    status: "Ready",
    sqft: "15,000",
    beds: 0,
    baths: 2,
    tag: "Logistics",
    description: "Large industrial warehouse with 20-ft clear height, loading bays, and 3-phase power. Prime logistics location near NH48.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1400&q=80",
  },

  // ── OFF-PLAN · RESIDENTIAL ──────────────────────────────────────────
  {
    title: "2 BHK at Lodha Palava Phase 3",
    price: "₹85 L",
    priceCr: 0.85,
    location: "Dombivli, Navi Mumbai",
    category: "off-plan",
    propertyFor: "residential",
    type: "Apartment",
    status: "Off Plan",
    sqft: "780",
    beds: 2,
    baths: 2,
    tag: "New Launch",
    description: "Early-bird pricing at Lodha Palava's newest phase. Smart township living with schools, hospital, and retail within the campus.",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "3 BHK at Godrej Reserve, Kandivali",
    price: "₹2.9 Cr",
    priceCr: 2.9,
    location: "Kandivali East, Mumbai",
    category: "off-plan",
    propertyFor: "residential",
    type: "Apartment",
    status: "Off Plan",
    sqft: "1,450",
    beds: 3,
    baths: 3,
    tag: "Pre-Launch",
    description: "Reserve pricing on Godrej's upcoming luxury residential tower adjacent to a forest buffer zone. Possession Q3 2027.",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "4 BHK Penthouse at Oberoi Sky Heights",
    price: "₹14 Cr",
    priceCr: 14,
    location: "Borivali West, Mumbai",
    category: "off-plan",
    propertyFor: "residential",
    type: "Penthouse",
    status: "Off Plan",
    sqft: "4,500",
    beds: 4,
    baths: 5,
    tag: "Ultra Luxury",
    description: "Limited-release penthouse collection by Oberoi Realty. Private elevator, sky lounge, and 360° views of the National Park.",
    image: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "2 BHK at Marathon Nexzone, Panvel",
    price: "₹68 L",
    priceCr: 0.68,
    location: "Panvel, Navi Mumbai",
    category: "off-plan",
    propertyFor: "residential",
    type: "Apartment",
    status: "Off Plan",
    sqft: "720",
    beds: 2,
    baths: 2,
    tag: "Affordable",
    description: "Smartly designed 2 BHK in Marathon's integrated township with RERA-approved payment plans and possession in 18 months.",
    image: "https://images.unsplash.com/photo-1630699144867-37acec97df5a?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "3 BHK at Piramal Vaikunth, Thane",
    price: "₹2.2 Cr",
    priceCr: 2.2,
    location: "Thane West, Thane",
    category: "off-plan",
    propertyFor: "residential",
    type: "Apartment",
    status: "Off Plan",
    sqft: "1,280",
    beds: 3,
    baths: 2,
    tag: "New Launch",
    description: "Piramal's newest Thane offering — sprawling 3 BHK with clubhouse, infinity pool, and podium garden. CLP payment plan available.",
    image: "https://images.unsplash.com/photo-1551361415-69c87624334f?auto=format&fit=crop&w=1400&q=80",
  },

  // ── OFF-PLAN · COMMERCIAL ──────────────────────────────────────────
  {
    title: "Office at One BKC Tower C",
    price: "₹18 Cr",
    priceCr: 18,
    location: "Bandra Kurla Complex, Mumbai",
    category: "off-plan",
    propertyFor: "commercial",
    type: "Office",
    status: "Off Plan",
    sqft: "4,200",
    beds: 0,
    baths: 5,
    tag: "Upcoming",
    description: "Upcoming Grade A office tower in BKC with LEED Platinum certification. Floor plates from 2,000 sq ft. Handover Q4 2026.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "Retail Unit at Palava City Mall",
    price: "₹1.1 Cr",
    priceCr: 1.1,
    location: "Dombivli, Navi Mumbai",
    category: "off-plan",
    propertyFor: "commercial",
    type: "Retail",
    status: "Off Plan",
    sqft: "420",
    beds: 0,
    baths: 1,
    tag: "Pre-Launch",
    description: "Ground-floor retail unit in Palava City's upcoming lifestyle mall. High footfall guaranteed by 1 lakh+ residents in the township.",
    image: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&w=1400&q=80",
  },
  {
    title: "IT Park Office in Navi Mumbai SEZ",
    price: "₹7.5 Cr",
    priceCr: 7.5,
    location: "Ghansoli, Navi Mumbai",
    category: "off-plan",
    propertyFor: "commercial",
    type: "Office",
    status: "Off Plan",
    sqft: "3,000",
    beds: 0,
    baths: 4,
    tag: "SEZ",
    description: "SEZ-notified IT park office with tax benefits. State-of-the-art building with fiber connectivity and 100% power backup.",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1400&q=80",
  },
];

export async function POST() {
  try {
    await connectDB();
    const col = Property;

    const docs = SEED_PROPERTIES.map((p) => ({
      id: makeId(),
      ...p,
      slug: makeSlug(p.title),
      active: true,
      createdAt: now,
      updatedAt: now,
    }));

    await col.insertMany(docs);

    return NextResponse.json(
      { message: `Seeded ${docs.length} properties successfully.`, count: docs.length },
      { status: 201 }
    );
  } catch (err) {
    console.error("[seed-properties]", err);
    return NextResponse.json({ message: "Seed failed.", error: String(err) }, { status: 500 });
  }
}
